"""Hermetic yt-dlp stub for the smoke suite.

Drop this directory at the head of ``PYTHONPATH`` when launching the
Curatables subprocess and ``import yt_dlp`` resolves here instead of
the real ~30 MB package. ``YoutubeDL.extract_info`` returns a
deterministic info dict for any URL and ``YoutubeDL.download`` writes
a 4-byte placeholder file at the configured ``outtmpl``. That is
enough surface for the smoke suite to walk
``/parent/add → preview → confirm → background download → ready``
without touching the network.

The shape of the info dict matches what ``app/backends/ytdlp.py``
projects onto :class:`VideoMetadata`. Every key referenced there is
populated; URLs that look like channel/playlist endpoints return an
``entries`` list so the channel/playlist branch in the backend is
exercisable too.
"""

from __future__ import annotations

import os
from typing import Any


_VIDEO_ID = "smokevid01"
_CHANNEL_TITLE = "Smoke Test Channel"
_VIDEO_TITLE = "Smoke Test Video"


def _looks_like_channel_or_playlist(url: str) -> bool:
    lowered = url.lower()
    return (
        "/channel/" in lowered
        or "/playlist" in lowered
        or "list=" in lowered
        or "/c/" in lowered
        or "@" in lowered.split("/")[-1]
    )


def _video_info(url: str) -> dict[str, Any]:
    return {
        "id": _VIDEO_ID,
        "title": _VIDEO_TITLE,
        "description": "Smoke test video — generated by the fake yt-dlp.",
        "duration": 30,
        "channel": _CHANNEL_TITLE,
        "uploader": _CHANNEL_TITLE,
        "extractor": "smoketest",
        "extractor_key": "Smoketest",
        "thumbnail": "https://example.com/smoke-thumb.jpg",
        "view_count": 42,
        "upload_date": "20260101",
        "webpage_url": url,
        "url": url,
    }


def _channel_info(url: str) -> dict[str, Any]:
    entries = [
        {
            "id": f"smokeitem{i:02d}",
            "title": f"Smoke Item {i}",
            "duration": 30 + i,
            "channel": _CHANNEL_TITLE,
            "uploader": _CHANNEL_TITLE,
            "extractor": "smoketest",
            "extractor_key": "Smoketest",
            "thumbnail": f"https://example.com/smoke-thumb-{i}.jpg",
            "view_count": 100 + i,
            "upload_date": "20260101",
            "webpage_url": f"{url}#item{i}",
            "url": f"{url}#item{i}",
            "description": f"Smoke item {i}.",
        }
        for i in range(1, 4)
    ]
    return {
        "_type": "playlist",
        "id": "smokechannel",
        "title": _CHANNEL_TITLE,
        "channel": _CHANNEL_TITLE,
        "uploader": _CHANNEL_TITLE,
        "extractor": "smoketest",
        "extractor_key": "Smoketest",
        "webpage_url": url,
        "entries": entries,
    }


class YoutubeDL:
    """Stand-in for ``yt_dlp.YoutubeDL``. Implements only the surface
    Curatables actually calls — ``__enter__`` / ``__exit__``,
    ``extract_info``, ``download``."""

    def __init__(self, opts: dict | None = None):
        self.opts = dict(opts or {})

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        return False

    def extract_info(self, url: str, download: bool = False) -> dict:
        if _looks_like_channel_or_playlist(url):
            return _channel_info(url)
        return _video_info(url)

    def download(self, urls: list[str]) -> None:
        """Write a placeholder mp4 at the configured outtmpl.

        Curatables passes ``outtmpl=str(output_dir / "video.%(ext)s")``;
        we replace ``%(ext)s`` with ``mp4`` and write 4 bytes there so
        ``StorageService.download`` finds the expected file at the
        end of the call.
        """
        outtmpl = self.opts.get("outtmpl", "video.%(ext)s")
        path = outtmpl.replace("%(ext)s", "mp4")
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "wb") as f:
            f.write(b"FAKE")
        return None
